service: desafio-stefanini
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create 
    events:
      - http:
          path: users
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: users
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: users/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: users/{id}
         method: delete
         cors: true

plugins:
- serverless-offline